#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Tue Feb 19 19:45:16 2013

import wx
from wxPython._controls import wxListItem

# begin wxGlade: extracode
# end wxGlade


class MainMenu(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainMenu.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Nova Captura", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Abrir Captura", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Guardar Captura", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Guardar Captura Como...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Sair", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Ficheiro")
        wxglade_tmp_menu = wx.Menu()
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Estastisticas")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.panel_1 = wx.Panel(self, -1)
        self.panel_2 = wx.Panel(self.panel_1, -1)
        self.label_nameOfInterface = wx.StaticText(self.panel_2, -1, "Nome da Interface:")
        self.panel_3 = wx.Panel(self.panel_1, -1)
        self.ListControl_Packge = wx.ListCtrl(self.panel_3, -1, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.panel_4 = wx.Panel(self.panel_1, -1)
        self.tree_ctrl_1 = wx.TreeCtrl(self.panel_4, -1, style=wx.TR_HAS_BUTTONS | wx.TR_NO_LINES | wx.TR_DEFAULT_STYLE | wx.SUNKEN_BORDER)
        self.panel_5 = wx.Panel(self.panel_1, -1)
        self.label_1 = wx.StaticText(self.panel_5, -1, "label_1")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainMenu.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((800, 715))
        self.panel_2.SetMinSize((800, 100))
        self.panel_2.SetBackgroundColour(wx.Colour(255, 0, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainMenu.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_1.Add(self.label_nameOfInterface, 0, 0, 0)
        self.panel_2.SetSizer(grid_sizer_1)
        sizer_2.Add(self.panel_2, 1, 0, 0)
        sizer_3.Add(self.ListControl_Packge, 1, wx.EXPAND, 0)
        
        #Adiciona os cabeçalhos das colunas
        self.ListControl_Packge.InsertColumn(0, 'No.', width=50)
        self.ListControl_Packge.InsertColumn(1, 'Tempo')
        self.ListControl_Packge.InsertColumn(2, 'Origem', width=125)
        self.ListControl_Packge.InsertColumn(3, 'Destino', width=125)
        self.ListControl_Packge.InsertColumn(3, 'Protocolo')
        self.ListControl_Packge.InsertColumn(3, 'Dimensão')
        
        self.ListControl_Packge.InsertStringItem(0, "teste")
        self.ListControl_Packge.SetStringItem(0, 1, "01/19/2010")
        self.ListControl_Packge.SetStringItem(0, 2, "USA")
        
       
        self.panel_3.SetSizer(sizer_3)
        sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)
        sizer_4.Add(self.tree_ctrl_1, 1, wx.EXPAND, 0)
        self.panel_4.SetSizer(sizer_4)
        sizer_2.Add(self.panel_4, 1, wx.EXPAND, 0)
        sizer_5.Add(self.label_1, 0, 0, 0)
        self.panel_5.SetSizer(sizer_5)
        sizer_2.Add(self.panel_5, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MainMenu
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MainMenu(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
